version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    