name: "CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./aplicacao
jobs:
  build:
    name: "Build da Aplicação"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker
        run: docker-compose up --build -d

      - name: Create Database
        run: docker-compose run app rake db:create

      - name: Database Migrations
        run: docker-compose run app rake db:migrate
        
      - name: Database Seed
        run: docker-compose run app rake db:seed
  test:
    name: "Teste da Aplicação"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reset Database
        run: docker-compose run app rake db:reset

      - name: Run Tests
        run: docker-compose run app rspec
  lint:
    name: "Lint da Aplicação"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Lint
        run: docker-compose run app bash -c "gem install rubocop; rubocop -A --fail-level F"